controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        logout:
            path: /logout
            controller: App\Controller\SecurityController::logout
    type: attribute
